apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-mq.openshift-operators: ""
  name: ibm-mq
  namespace: openshift-operators
spec:
  channel: v1.8
  installPlanApproval: Automatic
  name: ibm-mq
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-mq.v1.8.2
