kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mq-app-route
  namespace: ibmmq
spec:
  host: app2e-svrconn.chl.mq.ibm.com
  to:
    kind: Service
    name: queuemanager-ibm-mq
    weight: 100
  port:
    targetPort: 1414
  tls:
    termination: passthrough
