apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  labels:
    eventstreams.ibm.com/cluster: eventstreams
  name: commands.topic
  namespace: kafka
spec:
  config:
    min.insync.replicas: '1'
    retention.ms: '31536000000'
  partitions: 1
  replicas: 3
  topicName: MQ.COMMANDS
